### ISSUE TITLE
AK包名

### ISSUE THREAD

**Issue by renbingGitHub** [lovebing/react-native-baidu-map#10]
申请百度AK时包名是用自已的还是 这边的？

**Comment by renbingGitHub** [comment]
在RN里面用什么方式可以打印当前KEY是否正确

**Comment by lovebing** [comment]
要用自己的，demo只是一个示例。如何查看keystore的sha1,网上有很多教程，百度地图API文档上也有，你可以去看一下

**Comment by renbingGitHub** [comment]
相同的sha1、相同的包名生成的AK，在android代码里面运行就可以、在reactNative里就不行、只显示网格。郁闷啊

**Comment by lovebing** [comment]
默认情况下，debug keystore跟release keystore是不同的，你应该是没配置好，可以参考一下demo，里面的keystore和api key都是配置好的

**Comment by walkertong** [comment]
显示网格，是ak没配置对么？

**Comment by renbingGitHub** [comment]
不清楚、用android写的就可以

**Comment by walkertong** [comment]
我在Android studio里面运行也只是显示网格，试验了demo，也没运行起来，还需要去研究调用原理，😓，你申请的百度ak是Android类型的key吗？ @renbingGitHub

**Comment by walkertong** [comment]
问题解决了，用Android Studio打开后，看了日志记录，开始是需要设置ACCESS_NETWORK_STATE权限，然后模拟器运行提示 APP Scode码校验失败，加了权限，并用release版本运行（我只配了release版本的key），正常显示了地图

**Comment by renbingGitHub** [comment]
我也用Android Studio试试看下
