### ISSUE TITLE
初始化后只有空白网格，reload刷新直接就卡主了，变黑了

### ISSUE THREAD

**Issue by weinengjian** [lovebing/react-native-baidu-map#104]
![qq](https://cloud.githubusercontent.com/assets/23124071/26762247/ae44fb36-4971-11e7-80ae-0ff56b7bc622.png)

**Comment by weinengjian** [comment]
![ftwst_dih94 zaoiaw7 0hq](https://cloud.githubusercontent.com/assets/23124071/26762262/01afe074-4972-11e7-8ed6-13d611f8644d.png)

**Comment by weinengjian** [comment]
果然是权限问题，AndroidMainifest.xml 文件中权限这样添加
` 
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"></uses-permission>
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"></uses-permission>
    
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"></uses-permission>

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />`

**Comment by weinengjian** [comment]
果然是权限问题，
`
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"></uses-permission>
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"></uses-permission>
    
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"></uses-permission>

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
`

**Comment by weinengjian** [comment]
AndroidMainifest.xml 文件

**Comment by tt0226** [comment]
请问下  ，我改了  还是空白

**Comment by tt0226** [comment]
好了

**Comment by huxuhuxu1234** [comment]
怎么弄好的？我的也是空白，改了xml还是空白

**Comment by walkerXiong** [comment]
@tt0226 改好之后能否共享下方法

**Comment by tt0226** [comment]
@walkerXiong 空白格 一般要不是出在SHA1  不对  就是包名不一样 每台电脑的SHA1还不一样

**Comment by longmain** [comment]
注意百度key的问题。检查一下，应用是不是用的你申请时的包名。
有些时候，用生产包名申请了key，在demo包里用，就会是空白网格。
如果是这样的情况，iOS在XCode里把demo包里的Bundle Identifier改为申请key时用的，再编译一下就可以了。

**Comment by sheepmiee** [comment]
遇到这个坑了，搞了我一天。。sha1申请debug版的填写在发布版的就行，开发版的不用填，权限配置要写全，如下：

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

<uses-permission android:name="android.permission.INTERNET" />

<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_SETTINGS" />

<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.CALL_PHONE" />

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_GPS" />

**Comment by sheepmiee** [comment]
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

<uses-permission android:name="android.permission.INTERNET" />

<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_SETTINGS" />

<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.CALL_PHONE" />

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_GPS" />
