### ISSUE TITLE
BaiduMapAPI_Map/BMKMapView.h not found

### ISSUE THREAD

**Issue by dandingol03** [lovebing/react-native-baidu-map#105]
`react-native-baidu-map`: ^0.6.0
throw error in RCTBaiduMapView.h

**Comment by dandingol03** [comment]
works fine,**man**.i **fixed** it .never mind,**baby**!

**Comment by Jiujiale** [comment]
怎么解决的？

**Comment by ismjt** [comment]
@dandingol03 我也碰到这个问题了 请问你是怎么解决的呢？
