### ISSUE TITLE
marker出现多个和重叠

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [lovebing/react-native-baidu-map#11]
这个是什么原因导致的？我看来一下IOS代码，貌似每次设置marker都会去remove annatation？没办法直接更新marker的坐标么

**Comment by lovebing** [comment]
应该是可以的，不过我还没有实现

**Comment by lovebing** [comment]
你pull最新的代码了吗？

**Comment by liuhuapiaoyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/8020726/18694923/a35f66ee-7fe0-11e6-9bf6-2f31b2de70da.png)
这是你最新的代码呀 ~~~太好了 联系上作者了

**Comment by liuhuapiaoyuan** [comment]
可惜IOS不熟~好想直接给你改好了~

**Comment by lovebing** [comment]
这个不难的，我之前也没做过IOS

**Comment by walkertong** [comment]
@lovebing 我现在的一个需求是展示多个marker，现在只能支持一个marker，我看你之前那个版本的代码是支持多个marker的，为什么这个版本去掉了这个功能？

**Comment by lovebing** [comment]
原来的用于显示当前位置的marker，可以考虑加一个 markers的属性 @walkertong

**Comment by linxinzhe** [comment]
楼主加油呀～等着你的markers，这个非常有用！～

**Comment by lovebing** [comment]
@linxinzhe @liuhuapiaoyuan @walkertong 已增加 markers
