### ISSUE TITLE
 'RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by wuguanghai45** [lovebing/react-native-baidu-map#110]
RN 0.42
react-native-baidu-map 0.6

希望大神升级一下版本支持 RN 0.42

**Comment by bluesky0109** [comment]
遇到同样的问题，版本原因吗？

**Comment by bluesky0109** [comment]
![image](https://user-images.githubusercontent.com/8929364/27253592-2db3f9b6-53aa-11e7-8a4c-dd38dc8890db.png)
clone 下来的 demo 编译也报错

**Comment by wuguanghai45** [comment]
@bluesky0109 可以用git的方式安装 不走npm源
react-native-baidu-map:   https://github.com/lovebing/react-native-baidu-map.git

**Comment by chookg** [comment]
#import <React/RCTViewManager.h>
#import <React/RCTConvert+CoreLocation.h>

**Comment by Leadrive** [comment]
导入后，有可能把react-native清除了，可以重新执行一次npm install

#import "React/RCTViewManager.h"
#import "React/RCTConvert+CoreLocation.h"

**Comment by windy** [comment]
+1
