### ISSUE TITLE
Error while updating property 'markers' of a viewmanaged by:RCTBaiduMapView

### ISSUE THREAD

**Issue by krislee94** [lovebing/react-native-baidu-map#116]
同样的代码在ios可以运行。但是在安卓端就报错。
```
        componentWillMount(){
        var promise = Geolocation.geocode(city,address).then((data)=>{
            this.setState({
                center:{
                    longitude:parseFloat(data.longitude),
                    latitude:parseFloat(data.latitude)
                },
                markers:[
                    {
                        longitude:parseFloat(data.longitude),
                        latitude:parseFloat(data.latitude)
                    }
                ]
            })



        }).catch((error)=>{
            //获取当前位置的方法。Geolocation。
            var pro = Geolocation.getCurrentPosition().then((json)=>{

                this.setState({
                    zoom:18,
                    center:{
                        latitude:json.latitude,
                        longitude:json.longitude,
                    },
                    markers:[
                        {
                            longitude:json.longitude,
                            latitude:json.latitude,
                        }
                    ]

                })
            })
        })

    }
、、、
之后我在render里调用 MapView
```
                <MapView
                    trafficEnabled={this.state.trafficEnabled}
                    baiduHeatMapEnabled={this.state.baiduHeatMapEnabled}
                    zoom={this.state.zoom}
                    mapType={this.state.mapType}
                    center={this.state.center}
                    markers={this.state.markers}
                    style={styles.map}
                    //点击获得当前的地址。
                    onMapClick={(e)=>{
                        let json = JSON.stringify(e);
                        this.setState({
                            markers:[
                                {
                                    longitude:e.longitude ,
                                    latitude: e.latitude,
                                }
                            ]
                        })
                        let param = {
                            longitude:e.longitude ,
                            latitude: e.latitude,
                        }

                        DeviceEventEmitter.emit('krislee',param);

                    }}

                >
                </MapView>
```

**Comment by krislee94** [comment]
@lovebing 只在更新marker的时候会出现这样的问题，您知道如何解决吗，在安卓上

**Comment by Kariko** [comment]
@krislee94 请问您解决了这个问题了吗

**Comment by krislee94** [comment]
@Kariko 我不晓得你那是什么原因导致的。我是在setState的时候，要加上center ，zoom和markers。三者缺一不可。然后成功 ， 你试一下。good lucky

**Comment by Kariko** [comment]
@krislee94 好的，谢谢~(●'◡'●)
