### ISSUE TITLE
运行安卓报错（错误: 无法将类 BaiduMapPackage中的构造器 BaiduMapPackage应用到给定类型）

### ISSUE THREAD

**Issue by Geek-ch** [lovebing/react-native-baidu-map#127]
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/ch/Git/inCloud2/Inclouds/android/app/src/main/java/com/inclouds/MainApplication.java:38: 错误: 无法将类 BaiduMapPackage中的构造器 BaiduMapPackage应用到给定类型;
            new BaiduMapPackage(),
            ^
  需要: Context
  找到: 没有参数
  原因: 实际参数列表和形式参数列表长度不同
1 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by Geek-ch** [comment]
找到原因了，是多写了一个new BaiduMapPackage()，导致出错。问题关闭掉了。

**Comment by 25juan** [comment]
@Geek-ch  我也出现了这个错误了，请问你是怎么修改的呢？

**Comment by Geek-ch** [comment]
@25juan    我是因为多导入了一次产生的错误，你检查一下看看是不是这种情况
