### ISSUE TITLE
undefined is not an object PropTypes.bool

### ISSUE THREAD

**Issue by zhangporco** [lovebing/react-native-baidu-map#138]
React.PropTypes has moved into a different package since React v15.5.
https://reactjs.org/docs/typechecking-with-proptypes.html
please update as soon as possible readme and MapView.js file

**Comment by shaodushu** [comment]
请问你解决了嘛？

**Comment by zhangporco** [comment]
是的，你需要先安装
npm install --save prop-types
并将 js 目录下的 MapView.js 的源码
import React, {
    Component,
    PropTypes
} from 'react';
修改为：
import React, {
    Component
} from 'react';
import PropTypes from 'prop-types';

**Comment by zhangporco** [comment]
是的，你需要先安装
npm install --save prop-types
并将 js 目录下的 MapView.js 的源码
import React, {
Component,
PropTypes
} from 'react';
修改为：
import React, {
Component
} from 'react';
import PropTypes from 'prop-types';

- 

-

**Comment by zhangporco** [comment]
是的，你需要先安装

`npm install --save prop-types`

并将 js 目录下的 MapView.js 的源码

`
import React, {
Component,
PropTypes
} from 'react';
`

修改为：
`
import React, {
Component
} from 'react';
`
`
import PropTypes from 'prop-types';
`
