### ISSUE TITLE
markers 删除

### ISSUE THREAD

**Issue by walkertong** [lovebing/react-native-baidu-map#15]
markers功能加的快，测试了一下，完全满足我的应用要求，删除的代码稍微有点问题：
        if(options.size() < mMarkers.size()) {
            int start = options.size();
            for (int i = start; i < mMarkers.size(); i++) {
                mMarkers.get(i).remove();
                mMarkers.remove(i);
            }
        }
我改成了：
        if(options.size() < mMarkers.size()) {
            int end = options.size();
            int markerSize=mMarkers.size();
            for (int i = markerSize; i > options.size(); i--) {
                mMarkers.get(i-1).remove();
                mMarkers.remove(i-1);
            }
        }
另外，为什么点击marker，在我手机上会出现两个信息框？

**Comment by walkertong** [comment]
![11](https://cloud.githubusercontent.com/assets/1449095/19148191/18af1638-8bee-11e6-87e2-ff879ba612cf.jpg)

**Comment by lovebing** [comment]
@walkertong 这个应该是百度地图的bug

**Comment by walkertong** [comment]
应该是，有时候就不会出现。

**Comment by lovebing** [comment]
这个bug已修复
