### ISSUE TITLE
打开后页面上下滑动时，地图上面会出现一条很小的缝隙，先是手机屏幕上的东西

### ISSUE THREAD

**Issue by wangbingqiong** [lovebing/react-native-baidu-map#150]
<img width="339" alt="wx20171218-151932 2x" src="https://user-images.githubusercontent.com/18202889/34094143-dfba5b36-e406-11e7-9453-887f539c5862.png">
如上图所画位置，地图刚加载时，显示的是手机上好多app的相对位置图，大概不到一秒，android测试，RN0.50版本
<img width="339" alt="wx20171218-151932 2x" src="https://user-images.githubusercontent.com/18202889/34094310-a1728f14-e407-11e7-992f-a7cd2d026bfd.png">

**Comment by WangchuanShuo** [comment]
请问你是reactnative 哪个版本

**Comment by wangbingqiong** [comment]
@WangchuanShuo react 16.0.0   react-native 0.50.3

**Comment by wangbingqiong** [comment]
已解决
