### ISSUE TITLE
MainApplication  new BaiduMapPackage(getApplicationContext())

### ISSUE THREAD

**Issue by zhengcola** [lovebing/react-native-baidu-map#16]
求告知 这个怎么操作啊 小白求解
MainApplication  new BaiduMapPackage(getApplicationContext())

**Comment by lovebing** [comment]
你初始化一个 RN 项目，就会有 MainApplication.java 这个文件，具体可以参考 demo
react-native-baidu-map/demo/android/app/src/main/java/com/rn/MainApplication.java
