### ISSUE TITLE
最新的RN版本报错（SDK Build Tools revision (23.0.2) is too low），gradle的版本该升级了

### ISSUE THREAD

**Issue by neozo** [lovebing/react-native-baidu-map#185]
RN 0.55.4 编译报错，工程默认使用 gradle2.3.3，对应的 SDK Build Tools 是   25.0.0，修改 gradle2.2.3 后可以编译

The SDK Build Tools revision (23.0.2) is too low for project ':react-native-baidu-map'. Minimum required is 25.0.0

**Comment by lovebing** [comment]
已更新
