### ISSUE TITLE
xcode10 + rn0.57.7报错，无法集成的解决方案

### ISSUE THREAD

**Issue by jasonzhangdong** [lovebing/react-native-baidu-map#211]
我的环境是
xcode 10
react-native 0.57.7
react-native-baidu-map@0.6.0
iphone7 plus 11.4.1

千万要注意，不要安装最新版的react-native-baidu-map1.0.1这个直接不能用，有很多错误。作者应该还没有重构修复好已适应xcode10.

xcode10 + rn0.57.7报错，无法集成，原因是xcode10删除了libstdc++.6.0.9.tdb这个库，而作者又对这个插件ios端的重构没有完成，导致xcode10集成出错
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
大概的意思就是第三方的库没有link上

解决方案，从网上下载一个libstdc++.6.0.9.tdb 放到以下两个路径下

真机路径
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib

iphone虚拟器路径
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib

然后在clear build。
但是要注意，虚拟器调试还是报错，必须连接真机调试，才可以.

**Comment by Wjy1005** [comment]
你好，我想问下，我已经下载了libstdc++.6.0.9.tdb并且拷贝到两个地址，但是xcode上添加不了，请问该怎么处理

**Comment by qtzjzp** [comment]
这个问题还是没有解决么?模拟器暂时无法使用的问题

**Comment by lenvonsam** [comment]
我也遇到这个问题
如何解决？

**Comment by ljmkimqx** [comment]
+1
xcode9.3运行一切正常，升级到xcode10直接报错，一开始时6.0.9.tdb的错误，已经在xcode的相应两个路径都加上了这个文件，也包括libstdc++.tdb文件。然后build扔然报错
![1861547871686_ pic_hd](https://user-images.githubusercontent.com/30502832/51429815-af436580-1c4d-11e9-87ad-22dd8c4a68c1.jpg)
然后把Linked Frameworks and Libraries里的libRCTBaiduMap.a文件以及和百度地图相关的7个framework文件删掉后重新build就build Success了，但这样就没法使用百度地图了。请问有解决办法吗？尝试过很多方法了，升级到1.0.1也不行。升级到1.0.1后发现react-native-baidu-map/ios文件夹里多出了Pod文件夹和xcworkspace后缀的文件，但文档说明还是以前的，我就仍然按旧的方式在Xcode上配置，也是加了libRCTBaiduMap.a后如图片类型的错误(文档是否没更新)。然后网上继续找方法，有些人说用cocoapod集成，我也尝试了，首先把Linked Frameworks and Libraries里百度相关的都清掉，然后pod “BaiduMapKit”, '~> 4.1.1’, (xcode左边的Libraries我并没有删除RCTBaiduMap.xcodeproj),然后build, 能build成功，然后再添加回libRCTBaiduMap.a到Linked Frameworks and Libraries，项目直接build Faile,连错误没报红出来。有什么解决办法，项目急，我也弄了将近两天，好蛋疼啊

**Comment by IceTeddy** [comment]
我也同样遇到这个问题。。。。

**Comment by ljmkimqx** [comment]
xcode9.3 react-native-baidu-map0.6.0运行正常，但升级到xcode10后除了6.0.9那个错外，libRCTBaiduMap.a文件里一些.m文件的确报错了，不知道为什么，所以一加libRCTBaiduMap.a文件就报一堆.o文件的错。我现在的做法是，iOS我用cocoapod管理百度SDK(pod “BaiduMapKit”, '~> 4.1.1’), 然后就不引入.a文件了，把react-native-baidu-map/ios/RCTBaiduMap里的几个文件copy出来，拉到我工程的xcode里，然后运行一下，发现真的是这几个文件里的某些代码报错了，可以参考 https://blog.csdn.net/hsf_study/article/details/85120386 来做下修改。如果报找不到framework相关错误，可以在build setting里搜search,配置下framework路径(指到pods里面的sdk)。注意Appdelegate文件里用的百度地图类名好像改了。然后我这边能运行起来了，也没什么问题。现在只能等作者重构完成了。（现在xcode10配置里只有copy出来的几个文件以及cocoapod集成的sdk, 其他react-native-baidu-map相关的都没怎么引入）。希望能帮到人，我自己也折腾了几天，在别人指导下解决的。

**Comment by lovebing** [comment]
已修复，使用 podspec 集成

**Comment by jasonzhangdong** [comment]
@lovebing  已经修复，除了你说的pod集成之后，xcode 执行pod之后，报错"RCTBaiduMapViewManager.h" 找不到，那是不是还需要手动的去导入包。还有，是不是手动的添加这个包路径，Header Search Paths里面还要添加吗

**Comment by cynicok** [comment]
@jasonzhangdong 嗨，使用podspec集成后，报错"RCTBaiduMapViewManager.h" 找不到。
这个问题你那边解决了吗？

**Comment by KingAmo** [comment]
@jasonzhangdong @cynicok  你们解决 `RCTBaiduMapViewManager.h` 找不到的错误了没？我也遇到这个错误了。。。

**Comment by jasonzhangdong** [comment]
> @jasonzhangdong 嗨，使用podspec集成后，报错"RCTBaiduMapViewManager.h" 找不到。
> 这个问题你那边解决了吗？

我用的手动集成的方式，不用pod集成了，有坑
