### ISSUE TITLE
Can't import modules from index.js

### ISSUE THREAD

**Issue by mmabraham** [lovebing/react-native-baidu-map#212]
Following the Readme instructions, I am trying to import the modules with `import { MapView, MapTypes, Geolocation, Overelay } from 'react-native-baidu-map` however, I am getting the following error: 
```
error: bundling failed: Error: Unable to resolve module `./MapView` from `/Users/***/***/node_modules/react-native-baidu-map/index.js`: The module `./MapView` could not be found from `/Users/***/***/node_modules/react-native-baidu-map/index.js`...
```

I believe this was introduced in a recent commit when the path segment `./js` was removed. ( https://github.com/lovebing/react-native-baidu-map/commit/03d15bf063493e2481e680c6f03e72b9aa2bfd27#diff-168726dbe96b3ce427e7fedce31bb0bcL17 )

**Comment by lovebing** [comment]
Thanks, this issue was fixed.
