### ISSUE TITLE
Overlay模块没有加载成功

### ISSUE THREAD

**Issue by Eafy** [lovebing/react-native-baidu-map#219]
下载最新的Demo，进行测试验证，发现无法加载Overlay文件夹中模块。如下图所示：
![img_6139](https://user-images.githubusercontent.com/12604160/52773871-e9e6c500-3076-11e9-900f-ac6bc381c74d.PNG)

**Comment by Eafy** [comment]
而且在App.js中，Overlay.Marker或Overlay.InfoWindow，去掉其中一个能跑起来，但是没有效果，如果2个都写，则会出现上面的问题

**Comment by lovebing** [comment]
IOS 还没实现 Overlay，待优化，

**Comment by Eafy** [comment]
那请问iOS大概需要多久才能重新构建完成？

**Comment by milobluebell** [comment]
。。。。

**Comment by milobluebell** [comment]
3个月过去了。。。

**Comment by milobluebell** [comment]
@lovebing 大神能快搞一下不？

**Comment by KingAmo** [comment]
> IOS 还没实现 Overlay，待优化，

iOS现在还不支持 `marker` 吗？？

**Comment by Eafy** [comment]
已经自己做marker了，作者貌似都没时间更新。

**Comment by MobDevelop** [comment]
Can you share your code, please?

**Comment by Eafy** [comment]
> Can you share your code, please?

You can search for react-native-baidu-map-jm, this branch is for my project needs, but I don't know if you can use it.

**Comment by MobDevelop** [comment]
Thank you for your replying.
I want to show a marker in the ios Baidu-map.
But Baidu-map not working in ios version.
Does it work?

**Comment by Eafy** [comment]
> Thank you for your replying, Eafy.
> It was a great library. I can see Baidu-map, also polygon and circle in the ios Version.
> I want to show a marker in the ios Baidu-map. But marker not working in ios version.
> Does it work?

You can download the latest code from github and I have fixed the problem.

**Comment by MobDevelop** [comment]
Thank you.
And I found one issue. Does it work in Android?
It's not working in Android.

**Comment by Eafy** [comment]
> Thank you.
> And I found one issue. Does it work in Android?
> It's not working in Android.

It works on Android. But, example code has some problems.
I am working on a fix.
