### ISSUE TITLE
定位偏移很多

### ISSUE THREAD

**Issue by liupeng826** [lovebing/react-native-baidu-map#22]
这个定位偏移很多，是什么原因呢？存在火星坐标问题吗？？

**Comment by lovebing** [comment]
应该是你的设备定位不准确，Android版定位获取的是百度坐标，IOS版定位是先获取GPS坐标再转换为百度坐标。

**Comment by liupeng826** [comment]
很奇怪，我是IOS版的，我在componentDidMount的时候先调用了一下原生的定位，就没问题，定位很准，但是只要我把这部分删掉，百度就会产生偏移。
componentDidMount() {
		navigator.geolocation.getCurrentPosition(
			(position) => {
				let initialPosition = JSON.stringify(position);
				this.setState({initialPosition});
			},
			(error) => alert(error.message),
			{enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}
		);

		this.watchID = navigator.geolocation.watchPosition((position) => {
			let lastPosition = JSON.stringify(position);
			this.setState({lastPosition: lastPosition});
		});
	}

**Comment by lovebing** [comment]
定位获取的是百度坐标，相对GPS坐标是有偏移的
