### ISSUE TITLE
RN0.50.4 iOS xcode10编译出错

### ISSUE THREAD

**Issue by willinzhang** [lovebing/react-native-baidu-map#220]
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by gaoxiaosong1113** [comment]
请问您是怎么解决的这个问题

**Comment by xclidongbo** [comment]
@willinzhang  也遇到这个错误了. 怎么解决的?
