### ISSUE TITLE
作者你好，我在真机debug环境下定位正常，打正式包后，只显示网络

### ISSUE THREAD

**Issue by Jonauil** [lovebing/react-native-baidu-map#23]
// 构造
      constructor(props) {
        super(props);
        // 初始状态
        this.state = {
            mayType:MapTypes.NORMAL,
            zoom: 15,
            center: {
                longitude: 113.981718,
                latitude: 22.542449
            },
            markers: [{
                longitude: 113.981718,
                latitude: 22.542449,
                title: "Window of the world"
            },{
                longitude: 113.995516,
                latitude: 22.537642,
                title: ""
            }]
        };

          Geolocation.getCurrentPosition()
              .then(data => {
                  console.log('------------mapdata-------------------');
                  console.log(data);
                  Geolocation.reverseGeoCode(data.latitude,data.longitude)
                      .then(dataAddress=>{
                          console.log('------------reverseGeoCode-------------------');
                          console.log(dataAddress);
                          this.setState({
                              address: dataAddress.address,
                          });
                      }) .catch(e =>{
                      console.warn(e, 'error');
                  });
                  this.setState({
                      zoom: 18,
                      marker: {
                          latitude: data.latitude,
                          longitude: data.longitude,
                          title: "当前位置"
                      },
                      center: {
                          latitude: data.latitude,
                          longitude: data.longitude,
                          title:""
                      }
                  });
              })
              .catch(e =>{
                  console.warn(e, 'error');
              });

      }
 <MapView
                                zoomControlsVisible={false}
                                zoom={this.state.zoom}
                                mapType={this.state.mapType}
                                center={this.state.center}
                                marker={this.state.marker}
                                markers={this.state.markers}
                                style={styles.map}
                                onMapClick={(e) => {
                                }}
                            >
                            </MapView>

**Comment by lovebing** [comment]
通常 debug key 和 release key 是不一样的，你需要重新设置一下百度地图开放平台app的参数

**Comment by liupeng826** [comment]
我之前就是key用错了，出现过这个问题，如作者所说你可以查一下百度地图 key是否使用正确。

**Comment by Jonauil** [comment]
确实是我的发布版key填写错了，现在解决了，非常感谢。

**Comment by weinengjian** [comment]
大哥后来你是怎么好的呀，我的也是这样，但是我百度上是发布版sha1生成的AK,现在release.apk，debug.apk都不行，都是这样的

**Comment by weinengjian** [comment]
脸红，的确是sha1问题，
