### ISSUE TITLE
Attempt to invoke virtual method "java.lang.String android.os.Bundle.getString(java.lang.String)" on a null object reference

### ISSUE THREAD

**Issue by sdn785618859** [lovebing/react-native-baidu-map#230]
"react-native": "0.58.6", "react-native-baidu-map": "^1.0.6"
运行demo报错

**Comment by sdn785618859** [comment]
- 

- 

> [``](url
Duplicate of #)

**Comment by snowwindsand** [comment]
麻烦说一下如何解决的？

**Comment by jason102** [comment]
我也有這個問題，打開了新issue:
https://github.com/lovebing/react-native-baidu-map/issues/284

**Comment by jason102** [comment]
問題解決了！請看#240

需要先注冊API key，再設置AndroidManifest.xml
