### ISSUE TITLE
Geolocation.getCurrentPosition什么都不返回，好像没有发送请求

### ISSUE THREAD

**Issue by Darkincense** [lovebing/react-native-baidu-map#248]
app开发完然后打发布包，之后安装正式版的app，然后正常使用了七天，七天之这个getCurrentPosition获取经纬度的方法好像不管用了，什么请求都不发送，已经检查了手机，定位权限打开了，联网也都正常，但好像就是不走这个方法。。请教大神怎么解决？

**Comment by Darkincense** [comment]
必须得使用手机的应用管理清一下应用的缓存之后才能正常使用

**Comment by sizhuxuan** [comment]
我也遇到这个问题了，iOS端执行这个方法什么都不返回，Android端执行这个方法只返回经纬度，其他字段都是null

**Comment by Riant** [comment]
@sizhuxuan  +1

**Comment by YTentone** [comment]
我的ios也不执行这个函数...

**Comment by lovebing** [comment]
已修复

**Comment by sizhuxuan** [comment]
> @sizhuxuan +1

解决了嘛，老哥

**Comment by whhlulu** [comment]
解决了嘛，
哪个版本没问题？
好像我的也是用了几天 然后不行了？

**Comment by Darkincense** [comment]
解决了 是我的问题 使用的是另一个本地存储插件
