### ISSUE TITLE
CocoaPods 动态库和静态库混用，pod install失败

### ISSUE THREAD

**Issue by KingAmo** [lovebing/react-native-baidu-map#256]
Podfile文件里启用了` use_frameworks!`，`pod install` 报错

```
[!] The 'Pods-ReactNativeAppDemo' target has transitive dependencies that
 include statically linked binaries: 
(/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BMKLocationKit/framework/BMKLocationKit.framework, 
/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BaiduMapKit/BaiduMapKit/thirdlibs/libcrypto.a, 
/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BaiduMapKit/BaiduMapKit/thirdlibs/libssl.a, 
/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BaiduMapKit/BaiduMapKit/BaiduMapAPI_Base.framework, 
/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BaiduMapKit/BaiduMapKit/BaiduMapAPI_Cloud.framework, 
/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BaiduMapKit/BaiduMapKit/BaiduMapAPI_Map.framework, 
/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BaiduMapKit/BaiduMapKit/BaiduMapAPI_Search.framework, and 
/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-
app/ios/Pods/BaiduMapKit/BaiduMapKit/BaiduMapAPI_Utils.framework)

```

请问一下该怎么解决？
试了一下删除` use_frameworks!` ，报错：`RCTBaiduMapViewManager.h file not found`

**Comment by KingAmo** [comment]
我又试了保留Podfile中的`use_frameworks!`，然后在`node_modules/react-native-baidu-map/ios/react-native-baidu-map.podspec` 中加上 `s.static_framework = true`，`pod install` 成功了，但是项目运行报错`RCTBaiduMapViewManager.h file not found`

**Comment by KingAmo** [comment]
然后我把 `#import "RCTBaiduMapViewManager.h"` 改成 `#import "BaiduMapViewManager.h"`，下面的方法也要改  `[BaiduMapViewManager initSDK:@"key"]`，然后运行，又报了一堆错
```
Undefined symbols for architecture x86_64: "_JSObjectGetPrototype"
...
...
```
然后按照这个[issue](https://github.com/facebook/react-native/issues/23183#issuecomment-458106496)的解决办法，然后又跑，终于跑起来了，iOS端可以看到地图了

Android端也安装到手机上了，但是报错`Invariant Violation: requireNativeComponent: "BaiduMapView" was not found in the UIManager.`

**Comment by KingAmo** [comment]
```
Invariant Violation: requireNativeComponent: "BaiduMapView" was not found in the UIManager.
```
这个错误的原因找到了，Android studio 控制台报错：
```
java.lang.RuntimeException: Only one Looper may be created per thread
```
定位到报错的代码处，把
```
 Looper.prepare();
```
改为
```
if (Looper.myLooper() == null) { Looper.prepare(); }
```
谁能给这个库提个PR，包括ios的podspec加上` s.static_framework = true`

**Comment by mengerzhuanyong** [comment]
"react-native": "0.59.5",
"react-native-baidu-map": "^1.0.6",


打包报以下错误～有遇到过吗
Build system information
error: Multiple commands produce '/Users/menger/Library/Developer/Xcode/DerivedData/OneSports-gkjdftrzkzpjwrdzxlqeunnnxjmh/Build/Intermediates.noindex/ArchiveIntermediates/OneSports/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a':
1) Target 'React' has a command with output '/Users/menger/Library/Developer/Xcode/DerivedData/OneSports-gkjdftrzkzpjwrdzxlqeunnnxjmh/Build/Intermediates.noindex/ArchiveIntermediates/OneSports/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a'
2) Target 'React' has a command with output '/Users/menger/Library/Developer/Xcode/DerivedData/OneSports-gkjdftrzkzpjwrdzxlqeunnnxjmh/Build/Intermediates.noindex/ArchiveIntermediates/OneSports/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libReact.a'

Build system information
error: Multiple commands produce '/Users/menger/Library/Developer/Xcode/DerivedData/OneSports-gkjdftrzkzpjwrdzxlqeunnnxjmh/Build/Intermediates.noindex/ArchiveIntermediates/OneSports/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a':
1) Target 'yoga' has a command with output '/Users/menger/Library/Developer/Xcode/DerivedData/OneSports-gkjdftrzkzpjwrdzxlqeunnnxjmh/Build/Intermediates.noindex/ArchiveIntermediates/OneSports/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'
2) Target 'yoga' has a command with output '/Users/menger/Library/Developer/Xcode/DerivedData/OneSports-gkjdftrzkzpjwrdzxlqeunnnxjmh/Build/Intermediates.noindex/ArchiveIntermediates/OneSports/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'

**Comment by KingAmo** [comment]
@mengerzhuanyong 没遇到过诶.. clean 一下？

**Comment by mengerzhuanyong** [comment]
@KingAmo 我升级了cocoapods版本之后就没在报错了，但是debug打不开调试菜单了。。。
看了一下DevSupport也是pod进来了，为什么不能用了呀😂！～

**Comment by KingAmo** [comment]
> @KingAmo 我升级了cocoapods版本之后就没在报错了，但是debug打不开调试菜单了。。。
> 看了一下DevSupport也是pod进来了，为什么不能用了呀😂！～

我也打不开调试菜单了。。看看我写的临时的[解决办法](https://www.jianshu.com/p/2ff0d7f1b1df)

**Comment by KingAmo** [comment]
#231

**Comment by KingAmo** [comment]
#249

**Comment by mengerzhuanyong** [comment]
@@


> > @KingAmo 我升级了cocoapods版本之后就没在报错了，但是debug打不开调试菜单了。。。
> > 看了一下DevSupport也是pod进来了，为什么不能用了呀😂！～
> 
> @mengerzhuanyong 我也打不开调试菜单了。。看看我写的临时的[解决办法](https://www.jianshu.com/p/2ff0d7f1b1df)
可以的！～

**Comment by guohuihot** [comment]
> ```
> Invariant Violation: requireNativeComponent: "BaiduMapView" was not found in the UIManager.
> ```
> 
> 这个错误的原因找到了，Android studio 控制台报错：
> 
> ```
> java.lang.RuntimeException: Only one Looper may be created per thread
> ```
> 
> 定位到报错的代码处，把
> 
> ```
>  Looper.prepare();
> ```
> 
> 改为
> 
> ```
> if (Looper.myLooper() == null) { Looper.prepare(); }
> ```
> 
> 谁能给这个库提个PR，包括ios的podspec加上` s.static_framework = true`

请问你说的这个在哪里改？

**Comment by KingAmo** [comment]
@guohuihot `BaiduMapPackage`里面，其实你去`android studio` 的`logcat` 里面看一下，会有报错提示的.
