### ISSUE TITLE
Android端怎么配置API_KEY？

### ISSUE THREAD

**Issue by KingAmo** [lovebing/react-native-baidu-map#257]
README中只写了怎么配置iOS端的AK，Android端的怎么配置呢？

**Comment by KingAmo** [comment]
android 端貌似不需要配置百度地图的AK？

**Comment by KingAmo** [comment]
好吧，需要参考官方的文档。。在这里仅仅按照readme想跑起来，不可能。。

**Comment by tiyunchen** [comment]
https://www.jianshu.com/p/7ca4d7acb6d2
