### ISSUE TITLE
android版本定位有时会失效

### ISSUE THREAD

**Issue by void117** [lovebing/react-native-baidu-map#27]
运行demo后发现，刚开始点击定位按钮是可以定到设备坐标的，但是再次移动之后点击定位按钮就没有效果了。

**Comment by void117** [comment]
试了一下使用MapModule.moveToCenter(data.latitude, data.longitude, 15)就可以

**Comment by lovebing** [comment]
这是因为地图移动时，state.center的值没有变化，可以对 state.center加一个属性，每次更新时取随机值，如 `this.setState(center: {
                    latitude: data.latitude,
                    longitude: data.longitude,
                    rand: Math.random()
                  });`
