### ISSUE TITLE
Could not get unknown property 'bundleReleaseAar' for object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.

### ISSUE THREAD

**Issue by skylarklxlong** [lovebing/react-native-baidu-map#279]
**RN 0.60+
gradle-5.4.1-all.zip
com.android.tools.build:gradle:3.4.1
react-native-baidu-map: 1.0.7**

**在运行react-native run-android 时会出现报错，错误信息如下：
Where:
Build file 'E:\xxxxx\node_modules\react-native-baidu-map\android\build.gradle' line: 66
 What went wrong:
A problem occurred evaluating project ':react-native-baidu-map'.  
 Could not get unknown property 'bundleReleaseAar' for object of 
type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.**

**解决方法：
需要将publication {}块包含在project.afterEvaluate中
参考https://xbuba.com/questions/55864101**

**Comment by YTentone** [comment]
在哪了加啊...能不能截图加在哪了..

**Comment by lovebing** [comment]
加好了
`afterEvaluate {
                artifact bundleReleaseAar
            }`
