### ISSUE TITLE
找不到BaiduMapPackage

### ISSUE THREAD

**Issue by luwu1991** [lovebing/react-native-baidu-map#28]
在添加new BaiduMapPackage(getApplicationContext()) 这行代码时，发现比demo缺了这行代码import org.lovebing.reactnative.baidumap.BaiduMapPackage; 我将这行代码手动加上之后，发现无法引用这个文件，导致new BaiduMapPackage(getApplicationContext()) 整行代码也在AS中报错，请问这是有谁知道怎么修改吗？

**Comment by lovebing** [comment]
没有正确导入module

**Comment by luwu1991** [comment]
报错不影响，可以正常启动。
