### ISSUE TITLE
可以提供一些不用 pod 安装的帮助说明吗？

### ISSUE THREAD

**Issue by Riant** [lovebing/react-native-baidu-map#283]
毕竟很多项目还是基于 react-native link 的，为此再弄 pod 那一套，又要面临各种各样的问题，对于大量前端来说，确实吃力。

谢谢。

**Comment by lovebing** [comment]
已支持 react-native link，详见 README.md

**Comment by Riant** [comment]
嗯，之前就看过百度文档了，折腾了一会，但是发现还是会出现报 import 的文件/方法找不到之类的问题，所以也是放弃了。还是弄 pod 吧。
