### ISSUE TITLE
Attempt to invoke virtual method "java.lang.String android.os.Bundle.getString(java.lang.String)" on a null object reference

### ISSUE THREAD

**Issue by jason102** [lovebing/react-native-baidu-map#284]
你們好，我的中文不太好，謝謝大家的耐心！以前有人問這個問題，不過雖然issue已經closed，但是還沒有說怎麽解決，所以我再打開一個：
[https://github.com/lovebing/react-native-baidu-map/issues/230](https://github.com/lovebing/react-native-baidu-map/issues/230)

我多搜索問題，看到這個：
https://blog.csdn.net/jason_lewis/article/details/79878323

不過我沒有看懂他的解決方式。這個問題很嚴重，用react-native run-android的時候，第一次運行會收到這個錯誤，可是RELOAD后沒有了。問題是做 gradlew assembleRelease之後，一旦打開安裝好的apk，它就crash，不能RELOAD，用不了app。這樣無法使用這個module

react-native-cli: 2.0.1
react-native: 0.61.2
react-native-baidu-map: 1.0.7

錯誤細節：
```
Attempt to invoke virtual method "java.lang.String android.os.Bundle.getString(java.lang.String)" on a null object reference

init
null

c
null

a
null

initialize
null

init
BaiduMapPackage.java:63

createViewManagers
ReactInstanceManager.java:782

createUIManager
CoreModulesPackage.java:184

getModule
CoreModulesPackage.java:152
....
```
一年前我用了這模塊的舊版本，那個時候沒有這個錯誤。麻煩你們幫忙！

**Comment by lovebing** [comment]
可能 com.baidu.lbsapi.API_KEY 没配置好？
参考 example 的 AndroidManifest.xml
https://github.com/lovebing/react-native-baidu-map/blob/master/example/android/app/src/main/AndroidManifest.xml
增加以下 meta-data：
<meta-data
        android:name="com.baidu.lbsapi.API_KEY"
        android:value="xxxx" />

**Comment by jason102** [comment]
就是我的問題！能不能加上這個步驟在你的docs裏面？我都不知道我需要設置AndroidManifest.xml ! 真謝謝你幫我們開發這個很有用的模塊！
