### ISSUE TITLE
我升级完之后，程序报错，查了在MapView.js中this.props.children.length 这个对像不存在

### ISSUE THREAD

**Issue by yhaiquan** [lovebing/react-native-baidu-map#289]
render() {
    let childrenCount = 0;
      for (let i = 0; i < this.props.children.length; i++) {
        const child = this.props.children[i];
        if (child.length) {
          childrenCount += child.length;
        } else {
          childrenCount++;
        }

    }

我增加了     if (this.props.children!=null)  判断，不知是否有影响
我的版本是RN 0.59.10

**Comment by lovebing** [comment]
已修复，1.0.11
