### ISSUE TITLE
你好，请问定位蓝点和导航功能可以实现吗？

### ISSUE THREAD

**Issue by xubuhang** [lovebing/react-native-baidu-map#29]
1.你好，请问百度地图定位蓝点和导航功能可以实现吗？
2.~~而且点击locate按钮定位在非洲海边，我改了虚拟机的坐标还是在非洲海边，这是怎么回事？~~(换成真机就好了)
3.有接口可以获得定位的地址信息吗？（城市和具体地址）
4.地图上的marker的pop重复出现怎么解决？(Android虚拟机和真机上有)
<img width="251" alt="qq20161028-0 2x" src="https://cloud.githubusercontent.com/assets/4189632/19797501/08af13c8-9d1e-11e6-91ae-aa96f10ef633.png">
4.地图上的marker的pop有办法可以响应点击吗？

**Comment by lovebing** [comment]
1. 还未计划。
3. Android可以使用 Geolocation.getCurrentPosition(), IOS可用使用 Geolocation.getCurrentPosition()  + Geolocation.reverseGeoCode()
4. 已修复
5. 可以使用 onMarkerClick

**Comment by xubuhang** [comment]
@lovebing 对于3）我直接升级一下就可以了吗？执行'npm install react-native-baidu-map --save'就可以吗？

**Comment by lovebing** [comment]
可以，package.json里的dependencies版本改一下

**Comment by xubuhang** [comment]
@lovebing 4)依然存在。

**Comment by xubuhang** [comment]
@lovebing 城市是怎么获得的？我没有取到。
<img width="487" alt="qq20161031-1 2x" src="https://cloud.githubusercontent.com/assets/4189632/19846733/bec2ea76-9f7c-11e6-8ccf-8f6153ee7262.png">
<img width="650" alt="qq20161031-2 2x" src="https://cloud.githubusercontent.com/assets/4189632/19846735/bffd058e-9f7c-11e6-866d-0eba858cce3d.png">

**Comment by lovebing** [comment]
clean一下project，在真机里运行 看看
