### ISSUE TITLE
运行ios报错library not found for -lcrypto

### ISSUE THREAD

**Issue by boonook** [lovebing/react-native-baidu-map#290]
环境:mac 
        xcode:11.1
        react-native:0.61.2
        react-native-baidu-map:1.0.10
 
![28C27924-9B73-4E10-8339-DDE237F30F2D](https://user-images.githubusercontent.com/34494413/67309073-d2c57480-f52d-11e9-904e-c77e04b42caf.png)
![image](https://user-images.githubusercontent.com/34494413/67311286-dbb84500-f531-11e9-8680-f048f4d7e58a.png)

**Comment by musesfish** [comment]
怎么解决的
