### ISSUE TITLE
更新的最新版本(1.0.12)没有看到有计算位置信息功能（安卓端），而且运行会报错如下

### ISSUE THREAD

**Issue by DYwangxue** [lovebing/react-native-baidu-map#295]
> RN版本 0.60.4
> react-native-baidu-map版本 1.0.12
> 机型：安卓

> 报错如下：

:react-native-baidu-map@debug/compileClasspath': Could not download react-native.aar (com.facebook.react:react-native:0.61.2): No cached version available for offline mode

然后更改了module的RN版本为com.facebook.react:react-native:+才能正常运行

> 重要的是:   

更新的最新版本没有位置计算功能，缩放功能也没有，跟老版本一个样子，已经升级了两次都这样，作者是不是没有发布新版本啊

**Comment by lovebing** [comment]
还没发在网上

**Comment by lovebing** [comment]
还没发布

**Comment by DYwangxue** [comment]
> 还没发布
我之前自己加上的也能用，我看新版本有这个功能才升级下，结果你还没发布，那我再加上吧，什么时候发布呢

**Comment by lovebing** [comment]
已发布
