### ISSUE TITLE
点击地图上地点的标志或标题时，不会触发onMapClick方法。

### ISSUE THREAD

**Issue by luwu1991** [lovebing/react-native-baidu-map#30]
点击地图上地点的标志或标题时，不会触发onMapClick方法，点击没有这些信息的地方，是正常的，请求可以修改下吗？

**Comment by luwu1991** [comment]
应该是onClickedMapPoi 这个方法，在iOS上是可以使用的，不知道在安卓上能不能使用，等会测试下

**Comment by lovebing** [comment]
android没有这个方法，onMarkerClick 时触发一下 onMapClick 就可以了

**Comment by luwu1991** [comment]
@Override
            public void onMapClick(LatLng latLng) {
                mapView.getMap().hideInfoWindow();
                WritableMap writableMap = Arguments.createMap();
                writableMap.putDouble("latitude", latLng.latitude);
                writableMap.putDouble("longitude", latLng.longitude);
                sendEvent("onMapClick", writableMap);
            }

            @Override
            public boolean onMapPoiClick(MapPoi mapPoi) {
                return false;
            }

是onMapPoiClick这个方法，现在组件中直接返回false了，能不能改下，把这个方法添加下？

**Comment by luwu1991** [comment]
@Override
            public void onMapClick(LatLng latLng) {
                mapView.getMap().hideInfoWindow();
                WritableMap writableMap = Arguments.createMap();
                writableMap.putDouble("latitude", latLng.latitude);
                writableMap.putDouble("longitude", latLng.longitude);
                sendEvent("onMapClick", writableMap);
            }

            @Override
            public boolean onMapPoiClick(MapPoi mapPoi) {
                return false;
            }

是onMapPoiClick这个方法，现在组件中直接返回false了，能不能改下，把这个方法添加下？

**Comment by luwu1991** [comment]
@Override
            public void onMapClick(LatLng latLng) {
                mapView.getMap().hideInfoWindow();
                WritableMap writableMap = Arguments.createMap();
                writableMap.putDouble("latitude", latLng.latitude);
                writableMap.putDouble("longitude", latLng.longitude);
                sendEvent("onMapClick", writableMap);
            }

            @Override
            public boolean onMapPoiClick(MapPoi mapPoi) {
                return false;
            }

是onMapPoiClick这个方法，现在组件中直接返回false了，能不能改下，把这个方法添加下？

**Comment by luwu1991** [comment]
@Override
            public void onMapClick(LatLng latLng) {
                mapView.getMap().hideInfoWindow();
                WritableMap writableMap = Arguments.createMap();
                writableMap.putDouble("latitude", latLng.latitude);
                writableMap.putDouble("longitude", latLng.longitude);
                sendEvent("onMapClick", writableMap);
            }

            @Override
            public boolean onMapPoiClick(MapPoi mapPoi) {
                return false;
            }

是onMapPoiClick这个方法，现在组件中直接返回false了，能不能改下，把这个方法添加下？

**Comment by luwu1991** [comment]
@Override
            public void onMapClick(LatLng latLng) {
                mapView.getMap().hideInfoWindow();
                WritableMap writableMap = Arguments.createMap();
                writableMap.putDouble("latitude", latLng.latitude);
                writableMap.putDouble("longitude", latLng.longitude);
                sendEvent("onMapClick", writableMap);
            }

            @Override
            public boolean onMapPoiClick(MapPoi mapPoi) {
                return false;
            }

是onMapPoiClick这个方法，现在组件中直接返回false了，能不能改下，把这个方法添加下？

**Comment by luwu1991** [comment]
@Override
            public void onMapClick(LatLng latLng) {
                mapView.getMap().hideInfoWindow();
                WritableMap writableMap = Arguments.createMap();
                writableMap.putDouble("latitude", latLng.latitude);
                writableMap.putDouble("longitude", latLng.longitude);
                sendEvent("onMapClick", writableMap);
            }

            @Override
            public boolean onMapPoiClick(MapPoi mapPoi) {
                return false;
            }

是onMapPoiClick这个方法，现在组件中直接返回false了，能不能改下，把这个方法添加下？

**Comment by lovebing** [comment]
可以

**Comment by lovebing** [comment]
已加上

**Comment by luwu1991** [comment]
非常感谢！
