### ISSUE TITLE
reverseGeoCode not working on  Android

### ISSUE THREAD

**Issue by izhaoo** [lovebing/react-native-baidu-map#300]
code:
```
Geolocation.reverseGeoCode(39.910976, 116.413369).then(res => {
    console.log(res);
});
```

result:
```
{"errcode": -1}
```

**Comment by RaymondYe** [comment]
遇到同样的问题，请问解决了吗？

**Comment by chenyumiao** [comment]
也遇到了同样的问题，请问解决了吗？

**Comment by RaymondYe** [comment]
@chenyumiao 后面发现是网络原因，可以检查下，用模拟器的浏览器能否正常联网

**Comment by chenyumiao** [comment]
> @chenyumiao 后面发现是网络原因，可以检查下，用模拟器的浏览器能否正常联网

你好，我是用的真机调试的，联网正常。

**Comment by RaymondYe** [comment]
@chenyumiao Android studio 看报错，是否存在，key对不上的问题

**Comment by chenyumiao** [comment]
@RaymondYe ，你好，key应该是对应上的，因为Geolocation.getCurrentPosition()这个方法是好使的。

**Comment by RaymondYe** [comment]
@chenyumiao 你可以看看 Android studio 上的log 是否有什么报错

**Comment by chenyumiao** [comment]
@RaymondYe ，log没有报错信息，我用的 "react-native-baidu-map": "^1.0.26",这个版本，你也用的这个版本吗？

**Comment by RaymondYe** [comment]
@chenyumiao 对的。也是这个版本，正常使用

**Comment by sizhuxuan** [comment]
> @RaymondYe ，你好，key应该是对应上的，因为Geolocation.getCurrentPosition()这个方法是好使的。

老哥，解决了吗？我也碰到这个问题了

**Comment by RaymondYe** [comment]
我的一直正常呢，如果你遇到这个问题，建议看 Android studio 里面的控制台看看有没有报错

sizhuxuan <notifications@github.com> 于2020年3月5日周四 下午3:38写道：

**Comment by izhaoo** [comment]
> @chenyumiao 你可以看看 Android studio 上的log 是否有什么报错

log没报错，其他模块都是可以使用的，网络也没问题。

**Comment by jassonxian** [comment]
我也遇到这样的问题，有解决的没

**Comment by izhaoo** [comment]
Android Studio 跑了一下原生，确实是百度地图的key没验证成功，问题解决。

**Comment by jiayangyang1204** [comment]
@chenyumiao 我也是这类似的问题，Geolocation.getCurrentPosition()正常使用，Geolocation.geocode()就报错{"errcode": -1}，请问你解决了吗

**Comment by mcl950121** [comment]
问一下 1.0.37的版本还需要去android配置类似于link的操作吗？  还是只需要AndroidManifest文件下添加key就可以了

**Comment by zhaoo** [comment]
> 问一下 1.0.37的版本还需要去android配置类似于link的操作吗？  还是只需要AndroidManifest文件下添加key就可以了 

不用的，直接安装就好了。

**Comment by viciOO** [comment]
> Android Studio 跑了一下原生，确实是百度地图的key没验证成功，问题解决。

控制台报错了吗？怎么看key验证成功啊老哥
