### ISSUE TITLE
修改坐标后，ios的marker不会移动

### ISSUE THREAD

**Issue by Dobyc** [lovebing/react-native-baidu-map#319]
代码
![image](https://user-images.githubusercontent.com/26281029/71861535-a7682400-3131-11ea-8473-b8a79e43c2f4.png)

点击前效果
![image](https://user-images.githubusercontent.com/26281029/71861639-f7df8180-3131-11ea-9342-96591f9d2996.png)

点击后效果
![image](https://user-images.githubusercontent.com/26281029/71861556-b8b13080-3131-11ea-8177-fc8dbf86cf87.png)

**Comment by bojianyin** [comment]
的确 我也遇到了这个问题 marker位置只有初始化的时候可以  更改时 ios上不可以更新到新的点上  还有劳作者帮忙赶紧看一下吧 辛苦了😂😂😂

**Comment by objczl** [comment]
安卓的目前的版本可以移动marker的位置
iOS，需要在这里修改下代码 (我这段代码，只是移动地图上一个marker的位置), 我添加了一个
[centerTrackingEnabled](https://github.com/objczl/react-native-baidu-map/commit/edb2828747c14f9ec5737199cb45a95e11b1ae2c)属性，可以控制是否移动这个marker。
```
- (void)mapStatusDidChanged: (BMKMapView *)mapView {
    CLLocationCoordinate2D targetGeoPt = [mapView getMapStatus].targetGeoPt;		    CLLocationCoordinate2D targetGeoPt = [mapView getMapStatus].targetGeoPt;

    if (mapView.annotations.count > 0 && ((BaiduMapView *)mapView).centerTrackingEnabled) {
        BMKPointAnnotation *annotation = mapView.annotations[0];
        annotation.coordinate = targetGeoPt;
        return;
    }
 ...
}
```

**Comment by lovebing** [comment]
最新版本已修复此问题
