### ISSUE TITLE
在android模拟器和真机上都不能显示marker标志

### ISSUE THREAD

**Issue by FengXianSen** [lovebing/react-native-baidu-map#32]
工程中添加该百度地图依赖后，在android模拟器和真机上都不能显示marker标志，而在iOS的模拟器和真机上显示是正常的，我的RN版本是0.28的，请问有没有好的解决方案？

**Comment by lovebing** [comment]
提供一下更多详细的信息

**Comment by FengXianSen** [comment]
工程中添加该百度地图依赖后，在android版本上使用marker或markers属性时，就会出现上图中的error，但在iOS版本中可以正常使用；我的RN版本是0.28的，请问有没有好的解决方法？
