### ISSUE TITLE
iOS 无法刷新地图上的 markers

### ISSUE THREAD

**Issue by xiaoyouPrince** [lovebing/react-native-baidu-map#331]
iOS 上的大头针第一次创建地图的时候可以正常显示，但是修改大头针的数组，即重新 setMarkers 或者地图内部嵌入 <Overlay.Marker> 就无法再刷新新的 Markers。。

**Comment by xiaoyouPrince** [comment]
已经参考 #319 ，不是一个问题，希望作者看到能尽快修复一下，谢谢

**Comment by xiaoyouPrince** [comment]
@lovebing

**Comment by ghyzx** [comment]
Overlay.Polyline 也无法动态刷新，求解

**Comment by lovebing** [comment]
最新版已修复 overlay 属性更新的问题，原理是在 didSetProps 方法里需要更新 annotation 的属性
