### ISSUE TITLE
删除 Marker 的时候会红屏报错  

### ISSUE THREAD

**Issue by Raintdk** [lovebing/react-native-baidu-map#333]
当marker 减少时
Tring to remove a view index above child count .......   
this.setState({
                markers: markers
            })

{markers.map((item) => {
                        return (<Marker
                            title={'马老六'}
                            // icon={{ uri: 'https://mapopen-website-wiki.cdn.bcebos.com/homePage/images/logox1.png' }}
                            location={{
                                longitude: 116.32140276741646,
                                latitude: 39.99053966980557,
                            }}/>)
                    })}

**Comment by lovebing** [comment]
新版已修复
