### ISSUE TITLE
marker可否增加一些api

### ISSUE THREAD

**Issue by qq382724935** [lovebing/react-native-baidu-map#338]
点标记：
1. 支持图标颜色修改
2. 支持额外参数
3. onMarkerClick事件返回数据中携带额外参数

**Comment by lovebing** [comment]
1. iOS 支持 pinColor
2 和 3 可通过 Marker 的 onClick 回调处理。

**Comment by qq382724935** [comment]
看了最新的commit，感谢。1. 后期能兼容android就完美了
