### ISSUE TITLE
[!] The 'Pods-****' target has libraries with conflicting names: libcrypto.a and libssl.a.

### ISSUE THREAD

**Issue by fypyxz** [lovebing/react-native-baidu-map#339]
{
  "name": "myRN",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "an": "react-native run-android",
    "android": "react-native run-android",
    "io": "react-native run-ios",
    "start": "react-native start",
    "startnc": "react-native start --reset-cache",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@ant-design/icons-react-native": "^2.2.1",
    "@ant-design/react-native": "^3.3.0",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/datetimepicker": "^2.3.1",
    "@react-native-community/hooks": "^2.5.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/netinfo": "^5.8.0",
    "@react-native-community/slider": "^2.0.9",
    "@react-native-community/viewpager": "^1.1.7",
    "@react-navigation/bottom-tabs": "^5.2.6",
    "@react-navigation/drawer": "^5.4.1",
    "@react-navigation/material-bottom-tabs": "^5.1.8",
    "@react-navigation/material-top-tabs": "^5.1.8",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "@umijs/hooks": "^1.9.0",
    "antd-mobile-demo-data": "^0.3.0",
    "color-js": "^1.0.5",
    "crypto-js": "^4.0.0",
    "dva": "^2.4.1",
    "dva-core": "^2.0.2",
    "dva-loading": "^3.0.20",
    "moment": "^2.24.0",
    "portable-fetch": "^3.0.0",
    "qs": "^6.9.3",
    "react": "16.11.0",
    "react-native": "0.62.1",
    "react-native-action-button": "^2.8.5",
    "react-native-animatable": "^1.3.3",
    "react-native-autocomplete-input": "^4.1.0",
    "react-native-baidu-map": "^1.0.35",
    "react-native-camera": "^3.22.1",
    "react-native-check-box": "^2.1.7",
    "react-native-contacts": "^5.1.0",
    "react-native-device-info": "^5.5.4",
    "react-native-dropdownalert": "^4.2.1",
    "react-native-easy-toast": "latest",
    "react-native-exit-app": "^1.1.0",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-crop-picker": "^0.28.0",
    "react-native-image-zoom-viewer": "^2.2.27",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-marquee": "^0.3.2",
    "react-native-modal": "^11.5.6",
    "react-native-motion": "^1.0.5",
    "react-native-orientation": "^3.1.3",
    "react-native-picker": "^4.3.7",
    "react-native-qrcode-svg": "^6.0.3",
    "react-native-reanimated": "^1.8.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-safe-area-utility": "^1.0.0",
    "react-native-screens": "^2.4.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-storage": "^1.0.1",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-navigator": "^0.3.4",
    "react-native-text-input-mask": "^2.0.0",
    "react-native-textinput-effects": "^0.5.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^9.1.1",
    "react-native-wechat": "^1.9.12",
    "react-native-writebox": "^1.0.9",
    "react-redux": "^7.2.0",
    "reanimated-bottom-sheet": "^1.0.0-alpha.19",
    "tslib": "^1.11.1",
    "url": "^0.11.0",
    "url-search-params-polyfill": "^8.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/crypto-js": "^3.1.44",
    "@types/react": "^16.9.32",
    "@types/react-native": "^0.62.2",
    "@types/react-native-vector-icons": "^6.4.5",
    "@types/react-navigation": "^3.4.0",
    "@types/react-redux": "^7.1.7",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^25.2.6",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-react-native": "^4.0.1",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.1",
    "husky": "^4.2.3",
    "jest": "^25.2.7",
    "metro-react-native-babel-preset": "^0.59.0",
    "prettier": "^2.0.4",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

和OpenSSL-Universal库冲突，这样要怎么处理处理？

**Comment by lovebing** [comment]
这里提供了解决方法： https://github.com/lovebing/react-native-baidu-map-examples

**Comment by fypyxz** [comment]
1、首先package.json文件中删除"react-native-baidu-map"，然后yarn install,
2、然后到iOS目录下，pod install ,然后打开***.xcworkspace工程项目，删除Pods/OpenSSL-Universal/Static/Support Files/底下的libssl.a和libcrypto.a
3、然后返回上级目录，添加"react-native-baidu-map"，然后yarn install,
4、然后到iOS目录下，pod install --no-repo-update，就可以了

**Comment by GreatAuk** [comment]
> 这里提供了解决方法： https://github.com/lovebing/react-native-baidu-map-examples
方法无效 rn: 0.63.2
![image](https://user-images.githubusercontent.com/20253809/92124455-634c3100-ee30-11ea-8e69-23634848efac.png)

**Comment by xym100111100** [comment]
@fypyxz  您的思路可以，但似乎文件夹的路径已经改变现在 ，
1: npm   uninstall  react-native-baidu-map 
2:注意，如果ios/Pods/BaiduMapKit 文件夹还存在的要删掉
3:删除Pods/OpenSSL-Universal/lib/的两个文件libssl.a和libcrypto.a
4:pod install
5:npm install react-native-baidu-map 
6: cd ios  &  pod install

**Comment by inkCrazy** [comment]
> > 这里提供了解决方法： https://github.com/lovebing/react-native-baidu-map-examples
> > 方法无效 rn: 0.63.2
> > ![image](https://user-images.githubusercontent.com/20253809/92124455-634c3100-ee30-11ea-8e69-23634848efac.png)

这个方法是要手动删除 pod 缓存中的 BaiduMapKit/thirdlibs/ 下的文件，然后重新执行 pod install才有效

**Comment by IseeUDenis** [comment]
> pod install --no-repo-update

有效

**Comment by IseeUDenis** [comment]
> 1、首先package.json文件中删除"react-native-baidu-map"，然后yarn install,
> 2、然后到iOS目录下，pod install ,然后打开***.xcworkspace工程项目，删除Pods/OpenSSL-Universal/Static/Support Files/底下的libssl.a和libcrypto.a
> 3、然后返回上级目录，package.json文件中添加"react-native-baidu-map"，然后yarn install,
> 4、然后到iOS目录下，pod install --no-repo-update，就可以了

这个真的有效

**Comment by jiyunkeji** [comment]
> > > 这里提供了解决方法： https://github.com/lovebing/react-native-baidu-map-examples
> > > 方法无效 rn: 0.63.2
> > > ![image](https://user-images.githubusercontent.com/20253809/92124455-634c3100-ee30-11ea-8e69-23634848efac.png)
> 
> 这个方法是要手动删除 pod 缓存中的 BaiduMapKit/thirdlibs/ 下的文件，然后重新执行 pod install才有效

这个方法无效啊
