### ISSUE TITLE
地图显示空白，

### ISSUE THREAD

**Issue by testxin** [lovebing/react-native-baidu-map#34]
在AppDelegate.m中增加了initSDK传入AK，对照了几遍感觉是对的，IOS加载进来地图时空白的，Geolocation获取的到值，请问还有什么可能性，导致地图的map没渲染出来？

**Comment by lovebing** [comment]
一般是ak不对或跟 buildle id不匹配，你可以看一下 log

**Comment by 13409795771** [comment]
@testxin 同样的问题 ak写了 跟bucle id 一样  地图空白的   你解决了吗

**Comment by swb2016** [comment]
我之前也遇到了同样的问题，查看xcode的log信息，可以发现是mapapi.bundle没有添加正确，应该把这个文件放在Build Phases - Copy Bundle Resources 下面
