### ISSUE TITLE
The requested URL returned error: 502 Bad Gateway

### ISSUE THREAD

**Issue by liuyunqiang** [lovebing/react-native-baidu-map#341]
http://repo.codeboot.net/pod/http/react-native-baidu-map/1.0.20/source.zip The requested URL returned error: 502 Bad Gateway

**Comment by lovebing** [comment]
已修复

**Comment by YT1** [comment]
> 已修复
还是有问题啊/usr/bin/curl -f -L -o /var/folders/y1/_bg43rwx5g14v0dcn57g8pn00000gn/T/d20240514-52765-1fwtkee/file.zip http://repo.codeboot.net/pod/http/react-native-baidu-map/1.0.8/source.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'
