### ISSUE TITLE
怎样动态计算地图的显示区域？

### ISSUE THREAD

**Issue by ghyzx** [lovebing/react-native-baidu-map#343]
比如有一段跑步轨迹，希望屏幕上完整显示出来，center好计算，zoom怎么动态计算了？ 

用iOS原生SDK时，是像下面这样计算的，请问：RN里面有对应的方法吗？
BMKCoordinateSpan span = BMKCoordinateSpanMake(maxlat-minlat, longitude);
BMKCoordinateRegion region = BMKCoordinateRegionMake(center, span);
[_mapView setRegion:region animated:YES];

**Comment by lovebing** [comment]
1、 计算地图两点 (min(lat), min(lng)), (max(lat), max(lng)) 的距离（米）
2、计算地图显示区域对角形长度
3、根据 zoomLevel 跟比例尺的对应关系选择合适的 zoom 值。（http://lbsyun.baidu.com/index.php?title=androidsdk/guide/QA）
