### ISSUE TITLE
急需帮助，下载了一直不能用

### ISSUE THREAD

**Issue by benshayu2015** [lovebing/react-native-baidu-map#38]
E:\RNWorkSpace\react-native-baidu-map-master>npm install react-native-ba
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\huangwei
act-native-baidu-map"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install react-native-baidu-map as a dependency of i
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\RNWorkSpace\react-native-baidu-map-master\npm-debug.log

**Comment by lovebing** [comment]
你如果在github上下载，就不用 npm install了。在你的react native项目里使用npm install

**Comment by benshayu2015** [comment]
我这个就是下载下来以后再工程目录里面npm install的
