### ISSUE TITLE
隐私合规问题被打回

### ISSUE THREAD

**Issue by xyj321** [lovebing/react-native-baidu-map#390]
百度Android定位SDK自v9.2.9版本起增加了隐私合规接口，使用方式发生了改变，与旧版本不兼容，请务必确保用户同意隐私政策后调用setAgreePrivacy接口以进行SDK初始化之前的准备工作。
![image](https://user-images.githubusercontent.com/49394120/174274361-d73b8534-0c5b-4637-89a1-8bdee56daa19.png)

都是在.jar 包里面的.class文件的路径； 我的initSDK 已经是在同意隐私政策之后初始化的但平台审核还是不行。
是否应该更新啦！

**Comment by yylingsj** [comment]
朋友有没有解决呢？我的也是，只是在华为应用市场被拒，通过OPPO的隐私自动化检测功能检测出来的react-native-device-info和react-native-baidu-map通过系统API获取 android_id2次。但是，实际这2个SDK的初始化代码都是在用户同意隐私协议之后才调用的。
怀疑这2个插件是import的时候就获取了android_id，因此，把这2个插件的加载方式改成运行加载(require方式)，再次检测，果然是有效，但只是react-native-device-info的警告没有了，react-native-baidu-map由原来的2次变成了1次，检查了好几次代码，确认没有import方式加载react-native-baidu-map了，不知道这1次是哪里来的。

**Comment by xyj321** [comment]
换个账号，忘了这是共用账号，回复信息都能看到！ 看到别回了

**Comment by a728384698** [comment]
> 朋友有没有解决呢？我的也是，只是在华为应用市场被拒，通过OPPO的隐私自动化检测功能检测出来的react-native-device-info和react-native-baidu-map通过系统API获取 android_id2次。但是，实际这2个SDK的初始化代码都是在用户同意隐私协议之后才调用的。
> 
> 怀疑这2个插件是import的时候就获取了android_id，因此，把这2个插件的加载方式改成运行加载(require方式)，再次检测，果然是有效，但只是react-native-device-info的警告没有了，react-native-baidu-map由原来的2次变成了1次，检查了好几次代码，确认没有import方式加载react-native-baidu-map了，不知道这1次是哪里来的。

忘了上面用的是公用账号发的撤不了！ 看组件已经有两年没更新了！应该是组件中百度的原生SDK没更新！打开app自动获取android ID！新版合规的SDK有提供一个未init SDK前调用的方法setAgreePrivacy 组件这边没找到！ 一个方法就是看看高德地图是否是最新的。另一个就是写原生桥接JS。

**Comment by slowlyliu** [comment]
请问各位大佬，最后都解决了吗？  能分享一下具体的方案，给大家参考下不？

**Comment by foolzhang** [comment]
看了这些issue，简直☹️

**Comment by xclidongbo** [comment]
合规解决了吗？
