### ISSUE TITLE
Android cannot add component to MapView

### ISSUE THREAD

**Issue by Ghost233** [lovebing/react-native-baidu-map#4]
Android cannot add component to MapView
在Androidsh上无法添加新的View作为子界面

org.lovebing.reactnative.baidumap.BaiduMapViewManager cannot be cast to com.facebook.react.uimanager.ViewGroupManager

<MapView style={styles.map}>
  <Buttton label="普通地图" styles={{flex:1}} onPress={() => {
    MapModule.setMapType(MapTypes.NORMAL);
  }} />
  <Buttton label="卫星地图" styles={{flex:1}} onPress={() => {
    MapModule.setMapType(MapTypes.SATELLITE);
  }} />
</MapView>

![a5adc5c9-098d-446a-ad46-8b901bbe2532](https://cloud.githubusercontent.com/assets/888208/17695366/ce0563d4-63da-11e6-81ab-526467e8c0b0.png)

I try replace "BaiduMapViewManager extends SimpleViewManager" to "BaiduMapViewManager extends ViewGroupManager"
but all view i add is all under the the real BaiduMap render view, so they cannot display
我尝试将"BaiduMapViewManager extends SimpleViewManager"改成"BaiduMapViewManager extends ViewGroupManager"但是都失败了,因为百度地图实际的地图渲染层在我添加的按钮之上,导致他们无法显示
![f8aa5125-ad20-45e9-9508-b3a35e7f85ef](https://cloud.githubusercontent.com/assets/888208/17695338/a8247b32-63da-11e6-86d7-40662faa5fbb.png)

By the way, this is the best baidumapkit i've ever used.
顺便,这是我用过的最好的百度地图控件了,

I hope that you could help me.
我希望你能帮助我

**Comment by lovebing** [comment]
现在可以添加了。由于百度地图Android adk的限制，不能添加ViewGroup。你可以添加 Text，每个child要指定坐标，非常不灵活，见demo。建议通过其它方法实现你的需求

**Comment by Ghost233** [comment]
尝试了Demo,果然还是不行,我尝试其他方式去实现吧,谢谢了
