### ISSUE TITLE
符号找不到

### ISSUE THREAD

**Issue by BrooklynaT** [lovebing/react-native-baidu-map#42]
/MainApplication.java:29: 错误: 找不到符号
          new BaiduMapPackage(getApplicationContext())
                  ^
  符号: 类 BaiduMapPackage
1 个错误
:app:compileDebugJavaWithJavac FAILED

**Comment by lookerson** [comment]
在MainAppication.java这个文件的开头import org.lovebing.reactnative.baidumap.BaiduMapPackage 这个包试试
