### ISSUE TITLE
每次从地图切换到别的页面，或者别的页面切换到地图，都会露出背景图片

### ISSUE THREAD

**Issue by zzswang** [lovebing/react-native-baidu-map#49]
毫无头绪，any idea？

**Comment by lovebing** [comment]
背景图片？截个图上来看看？

**Comment by zzswang** [comment]
windowbackground, 是安卓app的背景图片

**Comment by zzswang** [comment]
现在换成 webview 了，重现不了，没法截图了。

大约就是，切换到地图页面，或者从地图页面切换到别的页面，会闪一下 app的背景图片。
