### ISSUE TITLE
 AndroidManifest.xml merge error

### ISSUE THREAD

**Issue by qazs** [lovebing/react-native-baidu-map#5]
[AndroidManifest.xml](https://github.com/lovebing/react-native-baidu-map/blob/master/android/src/main/AndroidManifest.xml) 里的以下代码会导致冲突, 建议去掉。
```
<meta-data
            android:name="com.baidu.lbsapi.API_KEY"
android:value="uDRdqQMGQeoPGn5CwMmIYicdUIVv1YST"/>
```

**Comment by lovebing** [comment]
这个是方便demo可以直接运行，不影响的

**Comment by walkertong** [comment]
去掉这个key配置在哪里呢？

**Comment by lovebing** [comment]
@walkertong 这个配置项目是必须配在AndroidManifest.xml里的

**Comment by jianweizhou** [comment]
和自己的key冲突啊，怎么解决

**Comment by lovebing** [comment]
忽略就好了

**Comment by NARUTOyuyang** [comment]
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
你有这个错吗

**Comment by lovebing** [comment]
@qazs 你是对的，已删除这个meta-data
@NARUTOyuyang 是meta-data重复的问题，已解决
