### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by LiuC520** [lovebing/react-native-baidu-map#50]
请问这个问题如何解决？
Undefined symbols for architecture arm64:
  "_BMKConvertBaiduCoorFrom", referenced from:
      -[GeolocationModule getBaiduCoor:lng:] in libRCTBaiduMap.a(GeolocationModule.o)
  "_BMKCoorDictionaryDecode", referenced from:
      -[GeolocationModule getBaiduCoor:lng:] in libRCTBaiduMap.a(GeolocationModule.o)
  "_BMKCoordinateRegionForMapRectInternal", referenced from:
      -[MapView updateTileLayerPara:] in BaiduMapAPI_Map(MapView.o)
      -[BMKMapView initSubView] in BaiduMapAPI_Map(BMKMapView.o)
      -[BMKMapView region] in BaiduMapAPI_Map(BMKMapView.o)
      -[BMKMapView setVisibleMapRect:animated:] in BaiduMapAPI_Map(BMKMapView.o)
  "_BMKGetMapApiBaseComponentVersion", referenced from:
      _BMKCheckMapComponentIsLegal in BaiduMapAPI_Map(BMKMapVersion.o)
  "_BMKGetNearestMapPointFromPolylineInternal", referenced from:
      -[BMKMapView checkOnClickedOverlayView:] in BaiduMapAPI_Map(BMKMapView.o)
  "_BMKMapRectContainsPointInternal", referenced from:
      -[BMKMapView isUserLocationVisible] in BaiduMapAPI_Map(BMKMapView.o)
  "_BMKMapRectIntersectsRectInternal", referenced from:
      -[BMKPolyline intersectsMapRect:] in BaiduMapAPI_Map(BMKPolyline.o)
      -[BMKMapView checkOverlayViews] in BaiduMapAPI_Map(BMKMapView.o)
  "_BMKMapRectNull", referenced from:
      -[BMKMapStatus init] in BaiduMapAPI_Map(BMKMapStatus.o)
      -[BMKMultiPoint init] in BaiduMapAPI_Map(BMKMultiPoint.o)
      -[BMKPolyline resetPoints:count:] in BaiduMapAPI_Map(BMKPolyline.o)
      -[BMKPolyline initWithPoints:count:textureIndex:] in BaiduMapAPI_Map(BMKPolyline.o)
      -[BMKPolygon resetPoints:count:] in BaiduMapAPI_Map(BMKPolygon.o)
      BMKMapRectIntersectionT(BMKMapRect, BMKMapRect) in BaiduMapAPI_Map(BMKMapView.o)
  "_BMKMapRectWorld", referenced from:
      -[BMKTileLayer init] in BaiduMapAPI_Map(BMKTileLayer.o)
      -[BMKMapView initSubView] in BaiduMapAPI_Map(BMKMapView.o)
  "_BMPointMake", referenced from:

**Comment by LiuC520** [comment]
有了解决方案，在百度官网下载了全部的新的包，然后把包里面的framework全部导入到xcode里面，并且在build seting 中的Library search paths里面添加$(SRCROOT)/../node_modules/react-native-baidu-map/ios/lib/thirdlibs，就可以了

**Comment by Xing-He** [comment]
@LiuC520  你好，我遇到跟你差不多的问题，然后根据你的做法还是报类似 `framework not found BaiduMapAPI_Base ...`的错误，我不懂ios，请问下你能贴个图是怎么弄得么，可以的话能加个Q吗 ： `1245036094`

**Comment by Xing-He** [comment]
`已解决`   
通过使用`pod`安装配置后就OK

[baidu map buildproject](http://lbsyun.baidu.com/index.php?title=iossdk/guide/buildproject)  

- 需要注意的是`Podfile`要指定版本,如：  
```
platform :ios,'10.2'
target "wabg" do
pod 'BaiduMapKit','~> 3.2.1'
end
```
