### ISSUE TITLE
rn 0.40 bugs

### ISSUE THREAD

**Issue by tigerohuang** [lovebing/react-native-baidu-map#51]
I met problem: Duplicate interface definition for class 'RCTBridge', and I solved it according to  the article:https://github.com/facebook/react-native/issues/11725, it was the problem of the changes in 0.40.

**Comment by FreAirLy** [comment]
怎么解决的呀？

**Comment by tigerohuang** [comment]
BaseModule.h修改前面的：
#import <React/RCTBridgeModule.h>
#import <React/RCTEventDispatcher.h>
#import <React/RCTBridge.h>

RCTBaiduMapView.h修改前面的：
#import <React/RCTViewManager.h>
#import <React/RCTConvert+CoreLocation.h>
#import <BaiduMapAPI_Map/BMKMapView.h>
#import <BaiduMapAPI_Map/BMKPinAnnotationView.h>
#import <BaiduMapAPI_Map/BMKPointAnnotation.h>
#import <UIKit/UIKit.h>

**Comment by liangjianyu** [comment]
楼上正解，我也解决了，本来想说一下的，结果楼上已经说出答案了。rn0.40.+改了目录结构，一些包迁移到react目录下。而且对双引号所以“。h”不支持了，要用<xx／xx.h>代替。其他第三方包遇到相同的情况时同理的

**Comment by lovebing** [comment]
fixed https://github.com/lovebing/react-native-baidu-map/pull/57
