### ISSUE TITLE
ios 定位当前位置GPS转换百度位置并没有作用

### ISSUE THREAD

**Issue by Xing-He** [lovebing/react-native-baidu-map#55]
- rn ： 0.41.2
- rn-baidu-map : 0.5.0
- 模拟器运行

应该是下面这段代码转换坐标的吧，搜了下网上的写法，好像一样的，但不知道这个为什么转换不了

```oc
-(CLLocationCoordinate2D)getBaiduCoor:(double)lat lng:(double)lng {
    CLLocationCoordinate2D coor = CLLocationCoordinate2DMake(lat, lng);
    NSDictionary* testdic = BMKConvertBaiduCoorFrom(coor,BMK_COORDTYPE_COMMON);
    testdic = BMKConvertBaiduCoorFrom(coor,BMK_COORDTYPE_GPS);
    CLLocationCoordinate2D baiduCoor = BMKCoorDictionaryDecode(testdic);
    
    return baiduCoor;
}
```

![1](https://cloud.githubusercontent.com/assets/11990205/23118667/eda8699a-f78f-11e6-83e8-96dc29eaeb00.png)

**Comment by xubuhang** [comment]
@Xing-He 你好，rn-baidu-map你可以在ios上运行吗？我的是rn0.41，ios项目代码报错找不到文件路径。你遇到吗？

**Comment by Xing-He** [comment]
@xubuhang  可以的，能具体点报什么错误吗，   #50  你参考下这个

**Comment by xubuhang** [comment]
<img width="742" alt="qq20170220-180817 2x" src="https://cloud.githubusercontent.com/assets/4189632/23120525/9c0f2a4e-f797-11e6-9e3d-cf8777ebbe79.png">

RCTBaiduMapViewManager.h file not found

**Comment by Xing-He** [comment]
- 已解决
模拟器不行，需要使用手机测试定位成功
