### ISSUE TITLE
RCTBundleURLProvider /RCTBaiduMapViewManager.h not found

### ISSUE THREAD

**Issue by xubuhang** [lovebing/react-native-baidu-map#56]
<img width="1050" alt="wx20170221-091438 2x" src="https://cloud.githubusercontent.com/assets/4189632/23146965/6d395562-f816-11e6-9a14-fcc40dc48f7e.png">
RCTBundleURLProvider/RCTBaiduMapViewManager.h not found

**Comment by kingfun2015** [comment]
@xubuhang 请问现在你有解决这个问题了吗？我这也遇到这个错误。

**Comment by xubuhang** [comment]
@kingfun2015 还没有解决，比较郁闷。

**Comment by kingfun2015** [comment]
@xubuhang 这会不会和版本有关啊，用的0.41最新版

**Comment by xubuhang** [comment]
我以前用"react-native": "0.35.0"集成的时候是可以运行的，现在用的是0.41就不行了。不兼容新版本。 @kingfun2015

**Comment by kingfun2015** [comment]
@xubuhang 那只能降低版本了，貌似这个封装组件的作者也很久没有更新了吧。

**Comment by xubuhang** [comment]
<img width="746" alt="wx20170227-173023 2x" src="https://cloud.githubusercontent.com/assets/4189632/23355822/7b979078-fd12-11e6-98e4-430b9d1f44bd.png">
试试看。 @kingfun2015
