### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by LitbLeo** [lovebing/react-native-baidu-map#6]
java.lang.ClassCastException: org.lovebing.reactnative.baidumap.BaiduMapViewManager cannot be cast to com.facebook.react.uimanager.ViewGroupManager

react-native的版本是0.31.0，不知道是为什么。

**Comment by lovebing** [comment]
是不是没更新代码？BaiduMapViewManager 现在是 extends ViewGroupManager的

**Comment by LitbLeo** [comment]
代码我是昨天下载的呀

**Comment by LitbLeo** [comment]
我的package.json文件里面显示的版本号：0.2.0，不知道你最新的版本是多少？我看你的也是0.2.0呀！但是对比了BaiduMapViewManager文件，我的确实没有继承ViewGroupManager。是不是版本的问题呢？

**Comment by lovebing** [comment]
是因为npm没同步，刚同步了。你更新一下

**Comment by LitbLeo** [comment]
嗯 我已经手动更新代码了！谢谢！
