### ISSUE TITLE
ios Geolocation.reverseGeoCode don't work 不执行

### ISSUE THREAD

**Issue by xubuhang** [lovebing/react-native-baidu-map#60]
console.log('=============');//此处打印
Geolocation.reverseGeoCode(39.910976, 116.413369).then(
                data=>{
                    console.log(data);//此处不打印
                }
            );
@Xing-He @MingYe-dz @lovebing

**Comment by Xing-He** [comment]
```js
Geolocation.reverseGeoCode(纬度,经度)
    .then(res => {
      console.log('reverseGeoCode',res);
      if(res&&res.code === 0){

      }else{
        console.log(res.message)
      }
    })
    .catch(e =>{
      console.warn(e, 'error');
    })
```

catch 打印下

**Comment by xubuhang** [comment]
Geolocation.getCurrentPosition()
          .then(data=>{
                    console.log(data);//打印
                }
            );
            console.log('=============');//打印
 Geolocation.reverseGeoCode(31.301612,120.672937)
                .then(res => {
                    console.log('reverseGeoCode',res);//不打印
                    if(res&&res.code === 0){
                    }else{
                        console.log(res.message)//不打印
                    }
                })
                .catch(e =>{
                    console.warn(e, 'error');//不打印
                });

Geolocation.reverseGeoCode里面什么都没有打印，这是怎么回事？@Xing-He @MingYe-dz @lovebing

**Comment by Xing-He** [comment]
![image](https://cloud.githubusercontent.com/assets/11990205/23442892/6ce0b262-fe66-11e6-9d34-91cae9e3eae8.png)

这个有调用没，打日志检查

**Comment by xubuhang** [comment]
<img width="699" alt="wx20170301-110921 2x" src="https://cloud.githubusercontent.com/assets/4189632/23444358/8f5c01da-fe6f-11e6-9c77-0a0ac71f384e.png">
@Xing-He @MingYe-dz @lovebing 请问是什么问题？

**Comment by xubuhang** [comment]
谢谢@Xing-He，我发现问题是Bundle Identifier不一致导致的。我修改本地Bundle Identifier，但是忘记修改百度开放网站上面的iOS  Bundle Identifier。粗心啊！
