### ISSUE TITLE
mark支持点击后显示浮窗吗？

### ISSUE THREAD

**Issue by LitbLeo** [lovebing/react-native-baidu-map#7]
mark支持点击后显示浮窗吗？

**Comment by LitbLeo** [comment]
如下图：
![image](https://cloud.githubusercontent.com/assets/5568469/17919698/04c57616-6a02-11e6-9bc5-0e323e56fc69.png)

**Comment by lovebing** [comment]
可以实现，但是现在还不支持

**Comment by LitbLeo** [comment]
嗯，我已经实现了，顺便问一问，MapView的childrenPoints的参数是什么意思呢？

**Comment by lovebing** [comment]
百度地图里添加子View需要指定经纬度坐标或屏幕坐标，比较麻烦。这个参数是一个数组，用于指定子View的屏幕坐标

**Comment by LitbLeo** [comment]
比如说您的例子中childrenPoints={[[330, 50], [580, 200]]}，这个数组的意思是什么？代表的是哪个子view呢？我一直搞不明白！

**Comment by lovebing** [comment]
按顺序，数组第几组坐标就对应第几个子View

**Comment by lovebing** [comment]
@LitbLeo marker已增加title属性，点击显示
