### ISSUE TITLE
地图是空白的

### ISSUE THREAD

**Issue by ShuBuShao** [lovebing/react-native-baidu-map#73]
大家好 地图是空白的 请问这是什么问题

**Comment by longyatmok** [comment]
昨天成功設定後也出現地圖空白的問題
iOS與安卓也是一樣…
iOS已經打開了HTTP，也是一樣空白
![baidu](https://cloud.githubusercontent.com/assets/3683723/24538027/3cd695bc-1619-11e7-8628-a61f4084dff2.png)

**Comment by CrazyShaQuiShi** [comment]
我的也是有没有什么解决方案啊

**Comment by CrazyShaQuiShi** [comment]
Hi， map is blank What is the problem

**Comment by dandingol03** [comment]
@ShuBuShao @longyatmok @CrazyShaQuiShi mapapi.bundle没放进去

**Comment by neo125874** [comment]
any solution about this problem? i do get the ak and sha1 from debug.keystore, but blank in android

**Comment by dandingol03** [comment]
@neo125874  have you put mapiapi.bundle in your xcode project?

**Comment by huahua112** [comment]
你要注意安全码？安全码和XCode及android的sha1都要和工程的对应起来，不然是调用不出来的！
![12312](https://cloud.githubusercontent.com/assets/12871226/25035623/3c6a4b92-2121-11e7-960a-afade835cd1d.png)

**Comment by yourenA** [comment]
@dandingol03 @huahua112 我在调试的时候地图可以显示出来，可是打包成apk在手机上上安装后就显示一片空白，请问一下为什么会出现这样

**Comment by yourenA** [comment]
@dandingol03 @huahua112 还有我在手机上安装apk的时候只有第一次定位返回有数据，后面就没有了

**Comment by dknightlx** [comment]
我之前也碰到了这个问题，现在已经解决。如果空白可能的问题是ak填错，或者meta-data放错地方。
可以尝试一下这个：
<application>
<meta-data android:name="com.baidu.lbsapi.API_KEY" android:value="xxxxxxxxxxxxxxxxxxx"/>
</application>
meta-data 放到application里面

**Comment by yourenA** [comment]
解决了
相信很多人在开发百度地图的时候会出现百度地图有时候会加载不出来，只显示网格图。 这个问题究其原因就是申请百度key的时候填写的SHA1也就是指纹证书有问题。估计很多开发者都是照着百度开放平台上介绍的流程去申请的。
　　当然，照着百度开放平台上去申请是没错的。但是上面介绍的申请得到的指纹证书只是本地开发环境存在的默认签名文件debug.keystore的指纹证书。流程如下：
　　第一步：打开命令窗口，输入cd .android。（这一步说明开发环境默认的签名证书debug.keystore存放在C盘.android目录中）
　　第二步：进入.android目录后，接着输入keytool -list -v -keystore debug.keystore，这里的debug.keystore就是开发环境下默认的签名文件了。
　　值得注意的是：我们在开发一个apk发布在应用商店时，需要我们自己的生成的签名文件，这个签名文件和开发环境默认的签名文件肯定是不同的，至少指纹证书SHA1就不同。所以，当我们通过我们自己生成的签名文件导出签名的apk时，百度地图的key应该是我们自己的签名文件中的指纹证书，如果还是用的是debug.keystore的SHA1申请的key,百度地图自然就会有问题。比如，我们导出apk的签名文件名字为myapp.keystore;那么可以通过在命令窗口中输入keytool -list -v -keystore myapp.keystore得到SHA1，然后通过这个SHA1去申请百度key，这样，你导出的签名apk的百度地图功能就不会只显示方格图加载不出来地图的问题了。
　　总之：如果你用到百度地图功能的apk，仅仅是通过本地环境运行的，你完全可以按照百度开放平台上介绍的流程去获取SHA1。但是，如果你开发的apk是需要自己生成的签名文件(签名证书)导出，放到应用商店去给别人下载的。那么，你申请百度地图key的SHA1值，就应该是来自你生成的签名文件中的SHA1值，SHA1查看方式keytool -list -v -keystore 签名文件。（注意要进入文件所在路径再输入命令）。
https://zhidao.baidu.com/question/937515725320609612.html

**Comment by neo125874** [comment]
@dknightlx  +1, i've stucked cuz of that issue, the position of meta-data, lol

**Comment by suano** [comment]
如何判断AK是否正确？我现在就是按照开放平台上设置的，但是在本地调试的时候还是只显示网格，也没有报错，都不知道哪里错了。。。

**Comment by annofy** [comment]
正确显示啦，配置问题

**Comment by weinengjian** [comment]
那到底是最后怎么解决的

**Comment by jinqiupeter** [comment]
我的iOS上一开始也是只显示网格，后来发现是apikey用了安卓的apikey。。
换成iOS的key就好了

**Comment by zza19900808** [comment]
个人是因为安卓的权限没给够才不显示地图只显示网格的,请再次确认权限是否足够

**Comment by Leadrive** [comment]
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"></uses-permission>
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"></uses-permission>
    
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"></uses-permission>

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />

把这些权限全 加上，就可以显示地图了，前提是你的api-key填对了。

**Comment by perfecten** [comment]
是否一定要真机？ 我在模拟机上只有网格。我确定SHA都提交了，AK也对了

**Comment by huahua112** [comment]
@perfecten  不需要真机，buiding ID ,这个比较重要，把这个弄好后基本就出来了

**Comment by perfecten** [comment]
谢谢@huahua112，应该是用户在审核的问题，昨天空白的地图，今天百度用户审核通过了，demo程序的地图就看得到了。
不过用Genymotion是启动不了的，我用AVD Manager.exe来启动模拟器

**Comment by ZaL0-0** [comment]
@dandingol03  你说的这个mapapi.bundle 文件在哪里，遇到相同问题了，求解~

**Comment by sanriqing** [comment]
@dknightlx  太感谢了。。。我折腾了两天才注意到你这一句话！！！
