### ISSUE TITLE
显示网格、上面提示ViewGroup is not allowed(Android)

### ISSUE THREAD

**Issue by renbingGitHub** [lovebing/react-native-baidu-map#8]
显示网格、上面提示 ViewGroup is not allowed(Android)

This is not a good idea to add children view to Baidu MapView

**Comment by lovebing** [comment]
这只是在MapView里添加子View的一个示例，目前支持不是很好，不建议使用

**Comment by renbingGitHub** [comment]
去掉子View后、地图还是显示网格、单击事件这些是可以用的

**Comment by lovebing** [comment]
那是你api key不对

**Comment by renbingGitHub** [comment]
申请的key是不是要 认证后才可以？

**Comment by lovebing** [comment]
要跟App签名绑定，详见  百度地图开发文档

**Comment by renbingGitHub** [comment]
好的，多谢
