### ISSUE TITLE
使用getCurrentPosition定位存在反复情况

### ISSUE THREAD

**Issue by PatWu16** [lovebing/react-native-baidu-map#98]
使用getCurrentPosition定位有时可以返回数据，但有时返回又为空，请问有可能是什么原因

**Comment by yangweiwei12345** [comment]
我也遇到这个问题了，又解决方案了吗

**Comment by PatWu16** [comment]
@yangweiwei12345 目前还是这样，你有解决吗

**Comment by PatWu16** [comment]
@futurechallenger 经过确认，是第一次进去可以获取到定位，后面再获取便返回null，请问可能是什么原因

**Comment by PatWu16** [comment]
@lovebing 大牛，请问有可能是什么原因？救急哦

**Comment by meiwhu** [comment]
我也遇到了。。。我就说怎么老是定位到大海里面

**Comment by duanwencheng** [comment]
我也是遇到了，是第一次进去可以获取到定位，后面再获取便返回null，还没解决

**Comment by PatWu16** [comment]
@duanwencheng 
确保你的sha1码正确，还有就是在真机上；我是通过这两项改好的

**Comment by duanwencheng** [comment]
@PatWu16 是android真机，我明天到公司再检查一下sha1。

**Comment by duanwencheng** [comment]
@PatWu16 解决了，测试打包好的apk就可以了，因为sha1是relese版本
